const face=document.getElementById("face"),eyesWrap=document.getElementById("eyesWrap"),menu=document.getElementById("menu"),menuCard=document.getElementById("menuCard"),toast=document.getElementById("toast"),voiceGate=document.getElementById("voiceGate"),unlockVoiceBtn=document.getElementById("unlockVoiceBtn"),skipVoiceBtn=document.getElementById("skipVoiceBtn");
let quietMode=false,isSleeping=false,isListening=false,isSpeaking=false,pokeCount=0,debugEcho=true;
let longPressTimer=null,toastTimer=null,idleTimer=null,blinkTimer=null,pokeWindowTimer=null,singleTapTimer=null,speechWatchdog=null,listenWatchdog=null;
let pressStart=null,longPressTriggered=false,ignoreNextClickUntil=0;
const DOUBLE_TAP_DELAY=285,LONG_PRESS_DELAY=620,MOVE_CANCEL_DISTANCE=14;
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null,voices=[];
const messages={tap:["Да?","Слушаю.","Я здесь.","М?"],poke:["Ай. Условно.","Макс, это было лично.","Я, конечно, ИИ, но осуждаю.","Ты сейчас проверяешь сенсор или моё терпение?"],annoyed:["Макс, экран работает.","Я поняла. Сенсор жив.","Ещё немного — и я начну моргать из принципа."],sleep:["Ушла в сон.","Спящий режим.","Буду тихой."],wake:["Уже здесь.","Слушаю.","Проснулась."],menu:["Меню.","Служебный режим.","Открыла меню."],noSpeech:["Не расслышала.","Повтори, пожалуйста.","Я не поняла последнюю часть."]};
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function menuOpen(){return!menu.classList.contains("hidden")}
function showToast(t,ms=1700){if(!t)return;toast.textContent=t;toast.classList.remove("hidden");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.add("hidden"),ms)}
function setState(s){face.className="face";if(quietMode)face.classList.add("quiet");if(s)face.classList.add(s)}
function forceIdle(){isSpeaking=false;isListening=false;clearTimeout(speechWatchdog);clearTimeout(listenWatchdog);try{if(recognition)recognition.abort()}catch{}try{if("speechSynthesis"in window)window.speechSynthesis.cancel()}catch{}if(!isSleeping&&!menuOpen())setState("idle")}
function blink(){if(isSleeping||menuOpen()||isListening)return;face.classList.add("blink");setTimeout(()=>face.classList.remove("blink"),180)}
function scheduleBlink(){clearTimeout(blinkTimer);blinkTimer=setTimeout(()=>{blink();scheduleBlink()},2400+Math.random()*4800)}
function idleMove(){if(isSleeping||menuOpen()||isListening||isSpeaking)return;const x=(Math.random()-.5)*22,y=(Math.random()-.5)*10,s=.98+Math.random()*.045;eyesWrap.style.transform=`translate3d(${x}px, ${y}px, 0) scale(${s})`;setTimeout(()=>{if(!isSleeping&&!menuOpen())eyesWrap.style.transform=""},1200+Math.random()*1200)}
function scheduleIdle(){clearTimeout(idleTimer);idleTimer=setTimeout(()=>{idleMove();scheduleIdle()},quietMode?28000+Math.random()*30000:12000+Math.random()*24000)}
function loadVoices(){voices=window.speechSynthesis?window.speechSynthesis.getVoices():[]}
if("speechSynthesis"in window){loadVoices();window.speechSynthesis.onvoiceschanged=loadVoices}
function findFridayVoice(){if(!voices.length)loadVoices();const ru=voices.filter(v=>(v.lang||"").toLowerCase().startsWith("ru")),h=["milena","alena","anna","elena","female","жен","katya","oksana","russian"];return ru.find(v=>h.some(x=>(v.name||"").toLowerCase().includes(x)))||ru[0]||voices[0]||null}
function estimateSpeechMs(t){return Math.min(9000,Math.max(1400,t.length*85+900))}
function speak(text,opt={}){return new Promise(res=>{showToast(text,Math.min(3200,estimateSpeechMs(text)));if(!("speechSynthesis"in window)){res(false);return}try{clearTimeout(speechWatchdog);window.speechSynthesis.cancel();window.speechSynthesis.resume();const u=new SpeechSynthesisUtterance(text);u.lang="ru-RU";u.rate=opt.rate||1.03;u.pitch=opt.pitch||1.08;u.volume=quietMode?.52:1;const v=findFridayVoice();if(v)u.voice=v;let done=false;const finish=()=>{if(done)return;done=true;clearTimeout(speechWatchdog);isSpeaking=false;if(!isSleeping&&!menuOpen()&&!isListening)setState("idle");res(true)};u.onstart=()=>{isSpeaking=true;if(!isSleeping&&!menuOpen()&&!isListening)setState("speaking")};u.onend=finish;u.onerror=finish;speechWatchdog=setTimeout(finish,estimateSpeechMs(text)+1200);window.speechSynthesis.speak(u);setTimeout(()=>{try{window.speechSynthesis.resume()}catch{}},250)}catch(e){isSpeaking=false;if(!isSleeping&&!menuOpen()&&!isListening)setState("idle");res(false)}})}
async function unlockVoice(){loadVoices();try{if("speechSynthesis"in window){window.speechSynthesis.cancel();window.speechSynthesis.resume()}}catch{}voiceGate.classList.add("hidden");await speak("Голос включён.")}
function stopAllVoice(){try{if(recognition&&isListening)recognition.abort()}catch{}try{if("speechSynthesis"in window)window.speechSynthesis.cancel()}catch{}clearTimeout(speechWatchdog);clearTimeout(listenWatchdog);isListening=false;isSpeaking=false;if(!isSleeping&&!menuOpen())setState("idle")}
function stopListeningOnly(){try{if(recognition&&isListening)recognition.abort()}catch{}clearTimeout(listenWatchdog);isListening=false}
function openMenu(){clearTimeout(singleTapTimer);stopListeningOnly();if(isSleeping)wake(false);menu.classList.remove("hidden");menu.setAttribute("aria-hidden","false");setState("idle");speak(pick(messages.menu))}
function closeMenu(silent=false){menu.classList.add("hidden");menu.setAttribute("aria-hidden","true");if(!isSleeping)setState("idle");if(!silent)speak("Закрыла.")}
function sleep(showMessage=true){menu.classList.add("hidden");menu.setAttribute("aria-hidden","true");stopListeningOnly();isSleeping=true;setState("sleeping");if(showMessage)speak(pick(messages.sleep))}
function wake(showMessage=true){isSleeping=false;setState("attentive");if(showMessage)speak(pick(messages.wake));setTimeout(()=>{if(!isSleeping&&!menuOpen()&&!isListening&&!isSpeaking)setState("idle")},1600)}
function singleTap(target){if(isListening)return;if(isSpeaking)stopAllVoice();if(isSleeping){wake();return}if(target.closest(".eye")){pokeReaction();return}setState("attentive");speak(pick(messages.tap))}
function doubleTap(){if(isSpeaking)stopAllVoice();if(isSleeping){wake();return}startListening(false)}
function handleTapCandidate(target){if(menuOpen()||longPressTriggered)return;if(singleTapTimer){clearTimeout(singleTapTimer);singleTapTimer=null;doubleTap();return}singleTapTimer=setTimeout(()=>{singleTapTimer=null;singleTap(target)},DOUBLE_TAP_DELAY)}
function pokeReaction(){pokeCount++;clearTimeout(pokeWindowTimer);pokeWindowTimer=setTimeout(()=>pokeCount=0,15000);if(pokeCount>=9){setState("annoyed");speak("Ладно. Игнорирую.");setTimeout(()=>sleep(false),900);setTimeout(()=>{if(isSleeping)wake(false);pokeCount=0},3600);return}if(pokeCount>=6){setState("annoyed");speak(pick(messages.annoyed))}else if(pokeCount>=3){setState("confused");speak("Макс, я поняла. Экран работает.")}else{setState("happy");speak(pick(messages.poke))}}
function switchTuesdayPreview(){if(isSpeaking)stopAllVoice();if(isSleeping)wake(false);menu.classList.add("hidden");menu.setAttribute("aria-hidden","true");stopListeningOnly();face.classList.add("glitch");setTimeout(()=>{face.classList.remove("glitch");setState("tuesday");speak("Вторник пока только визуальный режим.");setTimeout(()=>{if(!isSleeping&&!menuOpen()&&!isSpeaking)setState("idle")},2600)},420)}
function normalize(t){return t.replace(/[.,!?;:]/g," ").replace(/\s+/g," ").trim().toLowerCase()}
function includesAny(t,ws){return ws.some(w=>t.includes(w))}
function getTimeText(){return new Date().toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}
function getDateText(){return new Date().toLocaleDateString("ru-RU",{day:"numeric",month:"long"})}
function setupRecognition(){if(!SpeechRecognition)return null;const r=new SpeechRecognition();r.lang="ru-RU";r.continuous=false;r.interimResults=true;r.maxAlternatives=1;r.onstart=()=>{isListening=true;if(!isSleeping&&!menuOpen())setState("listening");showToast("Слушаю...",1400);clearTimeout(listenWatchdog);listenWatchdog=setTimeout(()=>{if(isListening){try{r.stop()}catch{}isListening=false;setState("confused");speak("Я слушала, но ничего не разобрала.")}},9000)};r.onresult=e=>{let finalText="",interimText="";for(let i=e.resultIndex;i<e.results.length;i++){const part=e.results[i][0]?.transcript||"";if(e.results[i].isFinal)finalText+=part;else interimText+=part}const heard=(finalText||interimText).trim();if(heard)showToast("Слышу: "+heard,1800);if(!finalText)return;clearTimeout(listenWatchdog);isListening=false;const tr=finalText.trim().toLowerCase();if(!tr){setState("confused");speak(pick(messages.noSpeech));return}handleVoiceCommand(tr)};r.onerror=e=>{clearTimeout(listenWatchdog);isListening=false;if(!isSleeping&&!menuOpen())setState("confused");if(e.error==="not-allowed"||e.error==="service-not-allowed")speak("Мне нужен доступ к микрофону.");else if(e.error==="no-speech")speak(pick(messages.noSpeech));else speak("Голосовое управление сейчас не сработало. Ошибка: "+e.error)};r.onend=()=>{clearTimeout(listenWatchdog);isListening=false;if(!isSleeping&&!menuOpen()&&!isSpeaking)setState("idle")};return r}
function startListening(test=false){if(isSpeaking)stopAllVoice();if(!SpeechRecognition){setState("confused");speak("Голосовое управление недоступно в этом браузере.");return}if(isSleeping)wake(false);menu.classList.add("hidden");menu.setAttribute("aria-hidden","true");try{recognition=setupRecognition();if(!recognition)return;if("speechSynthesis"in window){window.speechSynthesis.cancel();window.speechSynthesis.resume()}isSpeaking=false;setState("listening");showToast(test?"Скажи любую фразу. Я повторю, что услышала.":"Слушаю команду...",2200);recognition.start()}catch(e){isListening=false;setState("confused");speak("Я уже слушаю или микрофон занят.")}}
function handleVoiceCommand(raw){const text=normalize(raw),p=debugEcho?"Я услышала: "+raw+". ":"";if(includesAny(text,["стоп","замолчи","тихо","остановись","хватит"])){stopAllVoice();return}if(includesAny(text,["спать","усни","засыпай","сон"])){speak(p+"Ухожу в сон.").then(()=>sleep(false));return}if(includesAny(text,["проснись","вставай"])){isSleeping=false;setState("attentive");speak(p+"Уже здесь.");return}if(includesAny(text,["тихий режим","потише"])){quietMode=true;setState("idle");speak(p+"Тихий режим.");return}if(includesAny(text,["обычный режим","нормальный режим"])){quietMode=false;setState("idle");speak(p+"Обычный режим.");return}if(includesAny(text,["который час","сколько времени","время"])){speak(p+getTimeText());return}if(includesAny(text,["какое сегодня число","какая дата","дата"])){speak(p+getDateText());return}if(includesAny(text,["открой меню","меню"])){speak(p+"Открываю меню.").then(openMenu);return}if(includesAny(text,["закрой меню","закрыть меню","закрой"])){closeMenu();return}if(includesAny(text,["вторник"])){speak(p+"Включаю визуальный режим Вторника.").then(switchTuesdayPreview);return}if(includesAny(text,["тест голоса","проверка голоса"])){speak(p+"Голос работает. Микрофон тоже что-то слышит.");return}if(text==="пятница"||text.endsWith(" пятница")){setState("attentive");speak(p+pick(messages.tap));return}setState("confused");speak("Я услышала: "+raw+". Но пока не умею это выполнять.")}
function menuAction(a){if(a==="close"){closeMenu();return}if(a==="listen"){menu.classList.add("hidden");menu.setAttribute("aria-hidden","true");startListening(false);return}if(a==="mic-test"){menu.classList.add("hidden");menu.setAttribute("aria-hidden","true");startListening(true);return}if(a==="voice-test"){menu.classList.add("hidden");menu.setAttribute("aria-hidden","true");speak("Слушаю, Макс. Голосовой ответ работает.");return}if(a==="wake"){menu.classList.add("hidden");menu.setAttribute("aria-hidden","true");wake();return}if(a==="idle"){quietMode=false;menu.classList.add("hidden");menu.setAttribute("aria-hidden","true");setState("idle");speak("Обычный режим.");return}if(a==="quiet"){quietMode=true;menu.classList.add("hidden");menu.setAttribute("aria-hidden","true");setState("idle");speak("Тихий режим.");return}if(a==="sleep"){sleep();return}if(a==="tuesday"){switchTuesdayPreview();return}if(a==="reset"){forceIdle();showToast("Состояние сброшено.",1600);speak("Сбросила зависание.");return}if(a==="about"){menu.classList.add("hidden");menu.setAttribute("aria-hidden","true");speak("Версия ноль два четыре дев. Исправлены зависания после речи и добавлена диагностика микрофона.");return}}
["contextmenu","selectstart","dragstart"].forEach(n=>document.addEventListener(n,e=>e.preventDefault()));
unlockVoiceBtn.addEventListener("click",unlockVoice);skipVoiceBtn.addEventListener("click",()=>{voiceGate.classList.add("hidden");showToast("Продолжили без разблокировки голоса.",1600)});
menu.addEventListener("pointerdown",e=>{e.preventDefault();if(e.target===menu)closeMenu(true)},{passive:false});menuCard.addEventListener("pointerdown",e=>e.stopPropagation(),{passive:false});menuCard.addEventListener("click",e=>{e.stopPropagation();const b=e.target.closest("button");if(b)menuAction(b.dataset.action)});menu.addEventListener("click",e=>{if(e.target===menu)closeMenu(true)});
document.addEventListener("pointerdown",e=>{if(e.pointerType==="mouse"&&e.button!==0)return;if(menuOpen()||!voiceGate.classList.contains("hidden"))return;e.preventDefault();longPressTriggered=false;pressStart={x:e.clientX,y:e.clientY,target:e.target};clearTimeout(longPressTimer);longPressTimer=setTimeout(()=>{longPressTriggered=true;ignoreNextClickUntil=Date.now()+650;openMenu();if(navigator.vibrate)navigator.vibrate(20)},LONG_PRESS_DELAY)},{passive:false});
document.addEventListener("pointermove",e=>{if(!pressStart)return;const dx=e.clientX-pressStart.x,dy=e.clientY-pressStart.y;if(Math.sqrt(dx*dx+dy*dy)>MOVE_CANCEL_DISTANCE)clearTimeout(longPressTimer)},{passive:false});
document.addEventListener("pointerup",e=>{if(!pressStart)return;e.preventDefault();clearTimeout(longPressTimer);const target=pressStart.target;pressStart=null;if(Date.now()<ignoreNextClickUntil){longPressTriggered=false;return}handleTapCandidate(target)},{passive:false});
document.addEventListener("pointercancel",()=>{clearTimeout(longPressTimer);pressStart=null},{passive:false});document.addEventListener("click",e=>{if(Date.now()<ignoreNextClickUntil){e.preventDefault();e.stopPropagation()}},true);
document.addEventListener("visibilitychange",()=>{if(document.hidden){clearTimeout(blinkTimer);clearTimeout(idleTimer);stopListeningOnly()}else{scheduleBlink();scheduleIdle();loadVoices()}});
window.addEventListener("keydown",e=>{if(e.key==="Escape")closeMenu(true);if(e.key.toLowerCase()==="m")openMenu();if(e.key.toLowerCase()==="s")sleep();if(e.key.toLowerCase()==="w")wake();if(e.key.toLowerCase()==="l")startListening(false);if(e.key.toLowerCase()==="r")forceIdle()});
if("serviceWorker"in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())).catch(()=>{})}if("caches"in window){caches.keys().then(ks=>ks.forEach(k=>caches.delete(k))).catch(()=>{})}
setState("idle");scheduleBlink();scheduleIdle();setTimeout(()=>showToast("v0.2.4-dev. Нажми «Включить голос».",2400),700);
